//---------------Dao Xuan Thai----------------//
var Namespace={Register:function(_Name){var chk=false;var cob="";var spc=_Name.split(".");for(var i=0;i<spc.length;i++){if(cob!=""){cob+=".";}cob+=spc[i];chk = this.Exists(cob);if(!chk){this.Create(cob);}}if(chk){throw "Namespace: "+_Name+" is already defined.";}},Create:function(_Src){eval("window."+_Src+" = new Object();");},Exists:function(_Src){eval("var NE = false; try{if("+_Src+"){NE = true;}else{NE = false;}}catch(err){NE=false;}");return NE;}}
Namespace.Register("TLib");
var LoadingImg='Images/Loading.gif';
var DateNames=new Array("Chủ nhật","Thứ hai","Thứ ba","Thứ tư","Thứ năm","Thứ sáu","Thứ bảy");
var WaitingMessage='Đang tải dữ liệu, vui lòng chờ trong giây lát...';
TLib.getObj=function(id){if(typeof id!='string'){return id;}if(typeof document.getElementById!='undefined'){return document.getElementById(id);}else if(typeof document.all!='undefined'){return document.all[id];}else if(typeof document.layers!='undefined'){return document.layers[id];}else{return null;}}
TLib.getSelectValue=function(id){return TLib.getObj(id).options[TLib.getObj(id).selectedIndex].value;}
TLib.getSelectText=function(id){return TLib.getObj(id).options[TLib.getObj(id).selectedIndex].text;}
TLib.trim=function(val){val=val.replace(/^\s+|\s+$/g,'');return val.replace(/\s+\s/g,' ');}
TLib.removeUnicode=function(val){val=val.toLowerCase();val=val.replace(/à|á|ạ|ả|ã|â|ầ|ấ|ậ|ẩ|ẫ|ă|ằ|ắ|ặ|ẳ|ẵ/g,"a");val=val.replace(/è|é|ẹ|ẻ|ẽ|ê|ề|ế|ệ|ể|ễ/g,"e");val=val.replace(/ì|í|ị|ỉ|ĩ/g,"i");val=val.replace(/ò|ó|ọ|ỏ|õ|ô|ồ|ố|ộ|ổ|ỗ|ơ|ờ|ớ|ợ|ở|ỡ/g,"o");val=val.replace(/ù|ú|ụ|ủ|ũ|ư|ừ|ứ|ự|ử|ữ/g,"u");val=val.replace(/ỳ|ý|ỵ|ỷ|ỹ/g,"y");val=val.replace(/đ/g,"d");val=val.replace(/!|@|%|\^|\*|\(|\)|\+|\=|\<|\>|\?|\/|,|\.|\:|\;|\'| |\"|\&|\#|\[|\]|~|$|_/g,"-");val=val.replace(/-+-/g, "-");val=val.replace(/^\-+|\-+$/g,"");return val;}
TLib.showDate=function(container,date){if(!date) date=new Date();var dateTemplate="{date}, {day}/{month}/{year}";dateTemplate=dateTemplate.replace("{date}",DateNames[date.getDay()]);dateTemplate=dateTemplate.replace("{day}",date.getDate());dateTemplate=dateTemplate.replace("{month}",date.getMonth()+1);dateTemplate=dateTemplate.replace("{year}",date.getFullYear());if(!container){document.write(dateTemplate);}else{container=TLib.getObj(container);if(container){container.innerHTML=dateTemplate;}}}
TLib.compareDate=function(val1,val2){var d1,d2;d1=new Date(val1);d2=new Date(val2);return d1<d2;}
TLib.compareEUDate=function(val1,val2){val1=TLib.EU2USdate(val1);val2=TLib.EU2USdate(val2);var d1,d2;d1=new Date(val1);d2=new Date(val2);return d1<d2;}
TLib.EU2USdate=function(val){var date='';if(TLib.isDate(val,'EU')){date=val.split('/')[1]+'/'+val.split('/')[0]+'/'+val.split('/')[2];}return date;}
TLib.US2EUdate=function(val){var date='';if(TLib.isDate(val,'US')){date=val.split('/')[1]+'/'+val.split('/')[0]+'/'+val.split('/')[2];}return date;}
TLib.addDate=function(num,date,type){if(!TLib.isDate(date,type)){alert('Date is not valid.');return;}var _d,_m,_y;if(type=='EU'){_d=parseFloat(date.split('/')[0]);_m=parseFloat(date.split('/')[1]);_y=parseFloat(date.split('/')[2]);}else if(type=='US'){_d=parseFloat(date.split('/')[1]);_m=parseFloat(date.split('/')[0]);_y=parseFloat(date.split('/')[2]);}else{alert('Date type is not valid.');return;}var dayofmonth=new Array(31,28,31,30,31,30,31,31,30,31,30,31);var _total=_d+num;if(_total<=dayofmonth[_m-1]){_d+=num;}else{var _tmp=_d+num;var _tmp1;if(_m==2){_tmp1 =((((_y%4)==0)&&((_y%100)!=0))||((_y%400)==0))?29:28;}else{_tmp1=dayofmonth[_m-1];}while(_tmp>_tmp1){_tmp=_tmp-_tmp1;_m++;if(_m>12){_m=1;_y++;}if(_m==2){_tmp1=((((_y%4)==0)&&((_y%100)!= 0))||((_y%400)==0))?29:28;}else{_tmp1=dayofmonth[_m-1];}}_d=_tmp;}var kq;if(type=='EU'){kq=(_d<10? '0'+_d:_d)+'/'+(_m<10? '0'+_m:_m)+'/'+_y;}else if(type=='US'){kq = (_m<10? '0'+_m:_m)+'/'+(_d<10? '0'+_d:_d)+'/'+_y;}return kq;}
TLib.showLoadingDialog=function(visible){if(!top.loadingDialog){var dialog=document.createElement("DIV");dialog.className="LoadingDialog";dialog.style.visibility="hidden";top.loadingDialog=dialog;var bar=document.createElement("DIV");dialog.bar=bar;bar.innerHTML="<img src='"+LoadingImg+"' alt='' style='margin-right: 5px; vertical-align: middle;'/>"+WaitingMessage;bar.className="LoadingBar";bar.style.visibility="hidden";document.body.appendChild(dialog);document.body.appendChild(bar);dialog.setLoadingBarPosition=function(){var body=(document.documentElement)?document.documentElement:document.body;this.bar.style.left=Math.round(body.scrollLeft+(body.clientWidth-this.bar.offsetWidth)/2)+"px";this.bar.style.top=Math.round(body.scrollTop+(body.clientHeight-this.bar.offsetHeight)/2)+"px";};dialog.scrollLoadingBar=function(e){if(this.timer){clearTimeout(this.timer);}this.setLoadingBarPosition();this.timer=setTimeout(this.getHandler(this,"scrollLoadingBar"),50);};dialog.getHandler=function(obj,name){return function(e){e=e||window.event;return obj[name](e);};};dialog.fadeOut=function(){};dialog.show=function(){this.style.height=(document.body.scrollHeight+20)+"px";this.style.width=(document.body.scrollWidth+15)+"px";this.style.visibility="visible";this.bar.style.visibility="visible";this.setLoadingBarPosition();this.timer=setTimeout(this.getHandler(this,"scrollLoadingBar"),50);};dialog.hide=function(){if(this.timer){clearTimeout(this.timer);}this.fadeOutTimer=setTimeout(this.getHandler(this,"fadeOut"),50);this.style.visibility="hidden";this.bar.style.visibility="hidden";}}if(visible){top.loadingDialog.show();}else{top.loadingDialog.hide();}}
TLib.setHomePage=function(url){if(!url){return false;}if (document.all){document.body.style.behavior='url(#default#homepage)'; document.body.setHomePage(url);return false;}else if(window.sidebar){if(window.netscape){try{netscape.security.PrivilegeManager.enablePrivilege("UniversalXPConnect");}catch(e){alert("this action was aviod by your browser,if you want to enable,please enter about:config in your address line,and change the value of signed.applets.codebase_principal_support to true");}}var prefs=Components.classes['@mozilla.org/preferences-service;1'].getService(Components.interfaces.nsIPrefBranch);prefs.setCharPref('browser.startup.homepage',url);return false;}}
TLib.goToUrl=function(url,target){if(url){if(target==''){window.location=url;}else{window.open(url);}}}
TLib.goLink=function(id,target){if(TLib.getObj(id)){var url=TLib.getObj(id).options[TLib.getObj(id).selectedIndex].value;if(url!=''){if(target==''){window.location=url;}else{window.open(url);}}}}
TLib.showPager=function(pageCount,currentPage,url){var pages=new Array();var startPage=0;var endPage=0;if(eval(pageCount)==1){TLib.getObj("showpager").display="none";return;}startPage=currentPage-2;if(startPage<0){startPage=0;}if(startPage+4<pageCount){endPage=startPage+4;}else{endPage=pageCount-1;}if(endPage-4<0){startPage=0;}else{startPage=endPage-4;}pages[pages.length]="<a class='Page' "+(pageCount>0?"href='"+url.replace("{page}",0)+"'":"")+">|&lt;</a>";pages[pages.length]="<a class='Page' "+(currentPage-1>=0?"href='"+url.replace("{page}",currentPage-1)+"'":"")+">&lt;</a>";for(var i=startPage;i<=endPage;i++){pages[pages.length]="<a class='"+(i==currentPage?"Current":"Page")+"' href='"+url.replace("{page}",i)+"'>"+(i+1)+"</a>";}pages[pages.length]="<a class='Page' "+(currentPage+1<pageCount?"href='"+url.replace("{page}",currentPage+1)+"'":"")+">&gt;</a>";pages[pages.length]="<a class='Page' "+(pageCount>0?"href='"+url.replace("{page}",pageCount-1)+"'":"")+">&gt;|</a>";document.write(pages.join("&nbsp;&nbsp;"));}
TLib.writeSupport=function(address,type,imgUrl){if(address==''){return;}if(type==''){document.write('<a href="ymsgr:sendIM?'+address+'"><img border="0" src="http://opi.yahoo.com/online?u='+address+'&m=g&t='+imgUrl+'&l=us" alt="" /></a>');}else if(type=='1'&&imgUrl!=''){document.write('<script type="text/javascript" src="http://download.skype.com/share/skypebuttons/js/skypeCheck.js"></script><a href="skype:'+address+'?call" ><img alt="" src="'+imgUrl+'" style="border:0px;" /></a>');}}
TLib.writeAdv=function(url,link,width,height,className,title,target){if(!url){return;}width=width?"width='"+width+"'":"";height=height?"height='"+height+"'":"";link=link?"href='"+link+"'":"";title=title?"title='"+title+"'":"";target=target?"target='"+target+"'":"";className=className?"class='"+className+"'":"";if(url.match(/.swf$/ig)){document.write("<embed src='"+url+"' quality='best' wmode='transparent' "+width+" "+height+" align='middle' allowScriptAccess='sameDomain' type='application/x-shockwave-flash' pluginspage='http://www.macromedia.com/go/getflashplayer' />");}else{document.write("<a "+className+"  "+link +" "+title+" "+target+"><img src='"+url+"' "+width+" "+height+" style='border:none'/></a>");}}
TLib.getParamFromUrl=function(name){var q=document.location.search;var i=q.indexOf(name+'=');if(i==-1){return false;}var r=q.substr(i+name.length+1,q.length-i-name.length-1);i=r.indexOf('&');if(i!=-1){r=r.substr(0,i);}return r.replace(/\+/g,' ');}
TLib.addCommas=function(val){val+='';x=val.split('.');x1=x[0];x2=x.length>1?','+x[1]:'';var rgx=/(\d+)(\d{3})/;while(rgx.test(x1)){x1=x1.replace(rgx,'$1'+'.'+'$2');}return x1 + x2;}
TLib.getRandomNumber=function(min,max,floatVal){var randVal=min+(Math.random()*(max-min));return typeof floatVal=='undefined'?Math.round(randVal):randVal.toFixed(floatVal);}
TLib.setFocus=function(id){if(!TLib.getObj(id)) return;TLib.getObj(id).focus();}
TLib.getTopPosition=function(target){var top=0;if(target.offsetParent){while(1){top+=target.offsetTop;if(!target.offsetParent){break;}target=target.offsetParent;}}else if(target.y){top+=target.y;}return top;}
TLib.getLeftPosition=function(target){var left=0;if(target.offsetParent){while(1){left+=target.offsetLeft;if(!target.offsetParent){break;}target=target.offsetParent;}}else if(target.x){left+=target.x;}return left;}
TLib.showMessage=function(target,message,autohide){var msg;var msgcontent;if(!top.message){var MSGTIMER=10;var MSGSPEED=5;var MSGOFFSET=1;var MSGHIDE=2;msg=document.createElement('div');msg.id='msg';msgcontent=document.createElement('div');msgcontent.id='msgcontent';document.body.appendChild(msg);msg.appendChild(msgcontent);msg.style.filter='alpha(opacity=0)';msg.style.opacity=0;msg.alpha=0;top.message=msg;msg.show=function(flag){var value;if(flag==1){value=msg.alpha+MSGSPEED;}else{value=msg.alpha-MSGSPEED;}msg.alpha=value;msg.style.opacity=(value/100);msg.style.filter='alpha(opacity='+value+')';if(value>=99){clearInterval(msg.timer);msg.timer=null;}else if(value<=1){msg.style.display="none";clearInterval(msg.timer);}};msg.hide=function(){var msg=TLib.getObj('msg');if(msg){if(!msg.timer){msg.timer=setInterval("top.message.show(0)",MSGTIMER);}}}}else{msg=TLib.getObj('msg');msgcontent=TLib.getObj('msgcontent');}msgcontent.innerHTML=message;msg.style.display='block';var msgheight=msg.offsetHeight;var targetdiv=TLib.getObj(target);targetdiv.focus();var targetheight=targetdiv.offsetHeight;var targetwidth=targetdiv.offsetWidth;var topposition=TLib.getTopPosition(targetdiv)-((msgheight-targetheight)/2);var leftposition=TLib.getLeftPosition(targetdiv)+targetwidth+MSGOFFSET;msg.style.top=topposition+'px';msg.style.left=leftposition+'px';clearInterval(msg.timer);msg.timer=setInterval("top.message.show(1)",MSGTIMER);if(!autohide){autohide=MSGHIDE;}window.setTimeout("top.message.hide()",(autohide*5000));}
TLib.isEmail=function(val){if(/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/.test(val)){return true;}return false;}
TLib.isEmpty=function(val){return TLib.trim(val)=='';}
TLib.isNumber=function(val){var reg=/^\d+$/;return (reg.test(val));}
TLib.isDate=function(val,timetype){var dateStr=TLib.trim(val);var i=dateStr.indexOf("/");var j=dateStr.indexOf("/",i+1);if((i==-1)||(j==-1)){return false;}if(timetype=='EU'){var day=parseInt(dateStr.substr(0, i),10);var month=parseInt(dateStr.substr(i+1,(j-i-1)),10);var year=parseInt(dateStr.substr(j+1),10);}else if(timetype=='US'){var month=parseInt(dateStr.substr(0,i),10);var day=parseInt(dateStr.substr(i+1,(j-i-1)),10);var year=parseInt(dateStr.substr(j+1),10);}if((month<1)||(month>12)){return false;}if(isNaN(day)||isNaN(month)||isNaN(year)||(year<0)){return false;}var DOM=31;switch(month){	case 2:{DOM=((((year%4)==0)&&((year%100)!=0))||((year%400)==0))?29:28;break;}case 4: case 6: case 9: case 11:{DOM=30;break;} default:{DOM=31;break;}}if((day <1)||(day>DOM)){return false};return true;}
TLib.isIpAddress=function(val){var reg=/^(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]\d|\d)(?:[.](?:25[0-5]|2[0-4]\d|1\d\d|[1-9]\d|\d)){3}$/;return (reg.test(val));}
TLib.isHexadecimal=function(val){var reg=/^#(?:(?:[a-f\d]{3}){1,2})$/i;return (reg.test(val));}
TLib.createCookies=function(name,val,days){if(days){var date=new Date();date.setTime(date.getTime()+(days*24*60*60*1000));var expires = "; expires="+date.toGMTString();}else{var expires="";document.cookie=name+"="+value+expires+"; path=/";}}
TLib.readCookies=function(name){var nameEQ=name+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' '){c=c.substring(1,c.length);}if(c.indexOf(nameEQ)==0){return c.substring(nameEQ.length,c.length);}}return null;}
TLib.eraseCookies=function(name){createCookie(name,"",-1);}
